### ISSUE TITLE
Incompatibility with Eclipse under Windows

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/git-privacy#26]
## Description

To run Git Hooks under Windows with Eclipse you have to have installed cygwin and have to have the cygwin `\bin` directory in your `%PATH%`.
Running git-privacy in a cygwin powered bash works fine.
But git-privacy fails when executed via Eclipse / EGit.
To me it looks like the working directory is passed as an absolute path (somehow concatenated with the cygwin based path?!) and the code can't handle it.
Looks like an Eclipse bug, but maybe we can also somehow handle it for now?
@cburkert WDYT?

EDIT: This should be an issue with the output of `git rev-parse --show-toplevel` in the cygwin environment when started through Eclipse, right?

## Stacktrace

```
Traceback (most recent call last):
  File "/usr/local/bin/git-privacy", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1665, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/gitprivacy/gitprivacy.py", line 110, in cli
    ctx.obj = GitPrivacyConfig(gitdir)
  File "/usr/local/lib/python3.8/site-packages/gitprivacy/gitprivacy.py", line 35, in __init__
    self.repo = git.Repo(gitdir, search_parent_directories=True)
  File "/usr/local/lib/python3.8/site-packages/git/repo/base.py", line 146, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /cygdrive/c/Users/jnerl/Desktop/git-privacy-demo/C:\Users/jnerl/Desktop/git-privacy-demo
```

**Comment by cburkert** [comment]
I don't think it's an issue with `rev-parse`. In fact, git-privacy would reject a non-existent path earlier when parsing the CLI parameters. At that stage the path seems good and valid.
I guess it's probably that GitPython tries to be smart with cygwin here and something goes wrong:
https://github.com/gitpython-developers/GitPython/blob/17643e0bd1b65155412ba5dba8f995a4f0080188/git/repo/base.py#L135

Or the cygwin handling fails if used with EGit because EGit interferes with GitPythons cygwin detection.
Do you have a @fapdash setup ready for debugging?

**Comment by fapdash** [comment]
Opened a bug for JGit: https://bugs.eclipse.org/bugs/show_bug.cgi?id=573992

**Comment by cburkert** [comment]
Issue: On Windows with cygwin git rev-parse --show-toplevel sometimes produces
Windows paths (e.g., when invokes via Eclipse in some unclear scenarios)
and sometimes POSIX paths.

Workaround: Since our relevant hook types are always called with the working
directory set to the top-level working directory anyway, we can
let git-privacy use the CWD by default and be safe.

**Comment by cburkert** [comment]
@fapdash Can you please report if the workaround works for you?

**Comment by fapdash** [comment]
> @fapdash Can you please report if the workaround works for you?

The workaround fixes the issue.
