### ISSUE TITLE
Encoded RealDate is off by +1h

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/git-privacy#8]
The `RealDate` shown via `git-privacy log` is one hour into the future.
When I save a commit without git-privacy the commit timestamp is correct, so it shouldn't be a problem of my git setup.
I looked at the raw epoch seconds and they're already wrong, so the error doesn't get introduced during decoding / parsing. My timezone offset is also properly detected and saved.
This is especially curious as the times seem to get loaded from the commit object: https://github.com/EMPRI-DEVOPS/git-privacy/blob/09581ed7878f0da0b598d21bd38c3dd6b2c73c4c/gitprivacy/encoder/msgembed.py#L22-L27

## Setup
Ubuntu 18.04
Python 3.6.9
git version 2.17.1
git-privacy 1.4

**Comment by cburkert** [comment]
@fapdash Thanks for reporting. I was able to reproduce it and am looking into it.

**Comment by cburkert** [comment]
@fapdash Thanks again. I was able to fix this issues for future redates. Unfortunately, the old encrypted dates will remain flawed. Nothing I can do there...

From the commit message:
> Earlier versions incorrectly converted dates to UTC timestamps before
encryption by using system timezone information instead of the
information encoded in the original Git timestamp.
As a result encrypted timestamps can be arbitrarily offset from the
original time depending on the difference in system timezone information
and commit timezone information at the moment of redating.
>
>Furthermore, the causal strftime function ignores DST offsets which
causes the above error to result in mostly 1h offsets during DST.
>
>The error is fixed for all redates made with this version or up.
Old encrypted dates cannot be corrected due to missing DST details.
